// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Models;

namespace api.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20190129131310_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("api.Models.Acesso_siaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Android_gourmet");

                    b.Property<string>("Android_pedidos");

                    b.Property<string>("Cnpj");

                    b.Property<string>("Contrato");

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("Data_hora_acesso");

                    b.Property<int>("Num_dispositivo");

                    b.Property<int>("Num_dispositivos_pedidos");

                    b.Property<string>("Numero_serie");

                    b.Property<string>("Observacao");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("Acesso_siaf");
                });

            modelBuilder.Entity("api.Models.Controle_acesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cnpj");

                    b.Property<DateTime>("Data_hora_acesso");

                    b.Property<string>("Ip");

                    b.Property<string>("Nome_fantasia");

                    b.Property<string>("Numero_serie");

                    b.Property<string>("Razao_social");

                    b.Property<string>("Status_aesso");

                    b.Property<string>("Tipo_contrato");

                    b.Property<string>("Tipo_versao");

                    b.Property<string>("Versao_siaf");

                    b.Property<string>("Versao_ws");

                    b.HasKey("Id");

                    b.ToTable("Controle_acesso");
                });

            modelBuilder.Entity("api.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Administrador");

                    b.Property<DateTime>("Data_desativacao");

                    b.Property<double>("Desativado");

                    b.Property<DateTime>("Log_atualizacao");

                    b.Property<DateTime>("Log_criacao");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.Property<string>("email");

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("api.Models.Usuario_permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Rotina");

                    b.Property<int>("Usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Usuario_id");

                    b.ToTable("Usuario_permissao");
                });

            modelBuilder.Entity("api.Models.Usuario_permissao", b =>
                {
                    b.HasOne("api.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
